
spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
